set(CMAKE_BINARY_DIR ${PROJECT_SOURCE_DIR}/CMakeFiles)
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY lib)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY lib)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY bin)

set(CMAKE_CXX_STANDARD 14)
set(PROJECT_SOURCE_DIR "src")
